import type { NextConfig } from "next";

const legacyCityRedirects = [
  "adana",
  "adiyaman",
  "afyonkarahisar",
  "agri",
  "aksaray",
  "amasya",
  "ankara",
  "antalya",
  "ardahan",
  "artvin",
  "aydin",
  "balikesir",
  "bartin",
  "batman",
  "bayburt",
  "bilecik",
  "bingol",
  "bitlis",
  "bolu",
  "burdur",
  "bursa",
  "canakkale",
  "cankiri",
  "corum",
  "denizli",
  "diyarbakir",
  "duzce",
  "edirne",
  "elazig",
  "erzincan",
  "erzurum",
  "eskisehir",
  "gaziantep",
  "giresun",
  "gumushane",
  "hakkari",
  "hatay",
  "igdir",
  "isparta",
  "istanbul",
  "izmir",
  "kahramanmaras",
  "karabuk",
  "karaman",
  "kars",
  "kastamonu",
  "kayseri",
  "kirikkale",
  "kirklareli",
  "kirsehir",
  "kilis",
  "kocaeli",
  "konya",
  "kutahya",
  "malatya",
  "manisa",
  "mardin",
  "mersin",
  "mugla",
  "mus",
  "nevsehir",
  "nigde",
  "ordu",
  "osmaniye",
  "rize",
  "sakarya",
  "samsun",
  "sanliurfa",
  "siirt",
  "sinop",
  "sivas",
  "sirnak",
  "tekirdag",
  "tokat",
  "trabzon",
  "tunceli",
  "usak",
  "van",
  "yalova",
  "yozgat",
  "zonguldak",
] as const;

const nextConfig: NextConfig = {
  async redirects() {
    return legacyCityRedirects.map((city) => ({
      source: `/${city}-guvenlik-sistemi-kurulumu`,
      destination: `/${city}/kamera-sistemi-kurulumu`,
      permanent: true,
    }));
  },
};

export default nextConfig;
